# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dacfbd2c8c18a8b1b801aaf483d2a0e0a292648361dbe91feba04812eb0bb3ced273804230fe619419eb6d0318cf5ff329bdd542c2dbdc5bde197a60207db3cf
  gmail_username:  bandaide015@gmail.com
  gmail_password:  ismelleggs

test:
  secret_key_base: 801a46a65687f174d4497810e7a5699767ab818b024a6d41bcc267b6ba7e24d2f36fc58a7cbaf292e6d0894ec23e47da7e083712fbb8e76d486f491b0354c650

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
